### ISSUE TITLE
Sudo-prompt

### ISSUE THREAD

**Issue by YugiFanGX** [zurgeg/linux-access#1]
Where should I Copy the sudo-prompt File to?

Running the Script tells me that No such directory is available.

**Comment by zurgeg** [comment]
You need to have installed NA before hand. Looks like you didn't do that. Either that or you didn't set `WINEPREFIX`. Invoke the script like this: `WINEPREFIX=~/.wine ./nafix.sh` replacing `~/.wine` with a proper wine prefix. You may need to run `WINEPREFIX=/path/to/prefix winecfg` to create it.

Also do note that at least on my machine, I can't get past the log in screen (the button stays loading forever), so this project is useless until i figure that out

**Comment by zurgeg** [comment]
Oh wait, I forgot to add a path in the script. Download it again and try now

**Comment by YugiFanGX** [comment]
I did Install NA.

Alright, I saw you already updated the cp command.

I tested it on my computer. I also get stuck at the loading circle. Don't See any login fields.

**Comment by zurgeg** [comment]
> I did Install NA.
> 
> Alright, I saw you already updated the cp command.
> 
> I tested it on my computer. I also get stuck at the loading circle. Don't See any login fields.

Hmm. Does it show "Installing dependencies"?

**Comment by YugiFanGX** [comment]
Sorry for the misunderstanding.

Yes the dependencies were installed.

But where the Login fields should be, it shows a black field.

Hope it soon gets fixed..
